export enum PermissionEnum {
     GET_USERS = 'GET USERS',
    CREATE_PROJECT = 'CREATE PROJECT',
    GET_PROJECT = 'GET PROJECT',
    UPDATE_PROJECT = 'UPDATE PROJECT',
    DELETE_PROJECT = 'DELETE PROJECT',
}