export enum RolesEnum {
	USER = 'USER',
	PROJECT_ADMIN = 'PROJECT_ADMIN',
	PROJECT_MEMBER = 'PROJECT_MEMBER',
	PROJECT_VIEWER = 'PROJECT_VIEWER',
	BOARD_ADMIN = 'BOARD_ADMIN',
	BOARD_MEMBER = 'BOARD_MEMBER',
	BOARD_VIEWER = 'BOARD_VIEWER',
}
