// Aggregated permission set for system-wide admins (can reuse in seed or guards)
export enum AdminPermissionEnum {
  // User
  GET_USERS = 'GET_USERS',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Project
  CREATE_PROJECT = 'CREATE_PROJECT',
  GET_PROJECT = 'GET_PROJECT',
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  INVITE_MEMBER = 'INVITE_MEMBER',

  // Board
  CREATE_BOARD = 'CREATE_BOARD',
  GET_BOARD = 'GET_BOARD',
  UPDATE_BOARD = 'UPDATE_BOARD',
  DELETE_BOARD = 'DELETE_BOARD',
  CREATE_LIST = 'CREATE_LIST',
  UPDATE_LIST = 'UPDATE_LIST',
  DELETE_LIST = 'DELETE_LIST',
  CREATE_CARD = 'CREATE_CARD',
  UPDATE_CARD = 'UPDATE_CARD',
  DELETE_CARD = 'DELETE_CARD',
}
