export enum BoardPermissionEnum {
	CREATE_BOARD = 'CREATE_BOARD',
	GET_BOARD = 'GET_BOARD',
	UPDATE_BOARD = 'UPDATE_BOARD',
	DELETE_BOARD = 'DELETE_BOARD',

	INVITE_MEMBER = 'INVITE_MEMBER',
	REMOVE_MEMBER = 'REMOVE_MEMBER',
	UPDATE_MEMBER_ROLE = 'UPDATE_MEMBER_ROLE',
	LEAVE_BOARD = 'LEAVE_BOARD',

	GET_LIST = 'GET_LIST',
	CREATE_LIST = 'CREATE_LIST',
	UPDATE_LIST = 'UPDATE_LIST',
	DELETE_LIST = 'DELETE_LIST',

	GET_CARD = 'GET_CARD',
	CREATE_CARD = 'CREATE_CARD',
	UPDATE_CARD = 'UPDATE_CARD',
	DELETE_CARD = 'DELETE_CARD',
}
