export enum BoardPermissionEnum {
  CREATE_BOARD = 'CREATE_BOARD',
  GET_BOARD = 'GET_BOARD',
  UPDATE_BOARD = 'UPDATE_BOARD',
  DELETE_BOARD = 'DELETE_BOARD',
  CREATE_LIST = 'CREATE_LIST',
  UPDATE_LIST = 'UPDATE_LIST',
  DELETE_LIST = 'DELETE_LIST',
  CREATE_CARD = 'CREATE_CARD',
  UPDATE_CARD = 'UPDATE_CARD',
  DELETE_CARD = 'DELETE_CARD',
}
