export enum ListPermissionEnum {
  GET_LIST = 'GET_LIST',
  CREATE_LIST = 'CREATE_LIST',
  UPDATE_LIST = 'UPDATE_LIST',
  DELETE_LIST = 'DELETE_LIST',
  GET_CARD = 'GET_CARD',
  CREATE_CARD = 'CREATE_CARD',
  UPDATE_CARD = 'UPDATE_CARD',
  DELETE_CARD = 'DELETE_CARD',
}
